package ui;

import java.util.List;
import javax.swing.JOptionPane;
import models.Usuario;
import models.UsuarioTipo;
import services.AccesoService;
import services.EstudianteService;
import services.ProfesorService;
import services.UsuarioService;
import services.UsuarioTipoService;

/**
 *
 * @author Facundo
 */
public class Login extends javax.swing.JFrame {
    private AccesoService accesoService;
    private UsuarioService usuarioService;
    private UsuarioTipoService usuarioTipoService;
    private EstudianteService estudianteService;
    private ProfesorService profesorService;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.accesoService = new AccesoService();
        this.usuarioService = new UsuarioService();
        this.usuarioTipoService = new UsuarioTipoService();
        this.estudianteService = new EstudianteService();
        this.profesorService = new ProfesorService();
        setLocationRelativeTo(null);
        setResizable(false);
        loadUserTypes();
        setVisible(true);
    }
    
    private void loadUserTypes() {
       List<UsuarioTipo> usuarioTipos = this.usuarioTipoService.mostrarTodos();
       for(UsuarioTipo usuario : usuarioTipos) {
           inputUserTypes.addItem(usuario.getTipo());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        titleUser = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        titlePassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        titleTypes = new javax.swing.JLabel();
        inputUserTypes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(428, 369));
        setMinimumSize(new java.awt.Dimension(428, 369));

        login.setMaximumSize(new java.awt.Dimension(408, 432));
        login.setMinimumSize(new java.awt.Dimension(408, 432));
        login.setPreferredSize(new java.awt.Dimension(408, 432));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Login Usuario");
        login.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 6, -1, -1));
        Title.getAccessibleContext().setAccessibleDescription("");

        titleUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleUser.setText("USUARIO");
        login.add(titleUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 81, -1, -1));

        inputName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputName.setBorder(null);
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        login.add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 111, 298, 22));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 133, 298, -1));

        titlePassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlePassword.setText("CONTRASEÑA");
        login.add(titlePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 151, -1, -1));

        inputPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputPassword.setBorder(null);
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        login.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 179, 298, 22));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setMinimumSize(new java.awt.Dimension(64, 15));
        jSeparator3.setPreferredSize(new java.awt.Dimension(64, 15));
        login.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 201, 298, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("No posees cuenta?");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        btnLogin.setText("Acceder");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setMaximumSize(new java.awt.Dimension(87, 23));
        btnLogin.setMinimumSize(new java.awt.Dimension(87, 23));
        btnLogin.setPreferredSize(new java.awt.Dimension(87, 23));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        login.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        btnRegister.setText("Registrarse");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        login.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 120, -1));

        titleTypes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleTypes.setText("TIPO USUARIO");
        login.add(titleTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        inputUserTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserTypesActionPerformed(evt);
            }
        });
        login.add(inputUserTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String nombreUsuario = inputName.getText();
        String contraseniaUsuario = inputPassword.getText();
        String tipoUsuarioSeleccionado = (String) inputUserTypes.getSelectedItem();
        UsuarioTipo usuarioTipo = this.usuarioTipoService.mostrarPorTipo(tipoUsuarioSeleccionado);
        Usuario usuario = new Usuario(nombreUsuario,contraseniaUsuario,usuarioTipo);
        Usuario usuarioBase = this.usuarioService.mostrarPorID(nombreUsuario);
        if(usuarioBase != null) {
            if(usuarioTipo.getTipo().equals(usuarioBase.getTipoUsuario().getTipo())) {
                if(this.accesoService.login(usuario)) {
                    if(this.estudianteService.mostrarPorIDUsuario(nombreUsuario) != null || this.profesorService.mostrarPorIDUsuario(nombreUsuario) != null){
                        dispose();
                        Menu menu = new Menu(); 
                        menu.setUsuarioLogueado(usuarioBase);
                    } else {
                        dispose();
                        LoadDataUser loadDataUser = new LoadDataUser();
                        loadDataUser.setUsuario(usuarioBase);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Alerta", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tipo de usuario incorrecto", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nombre de usuario incorrecto", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        Register register = new Register();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void inputUserTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserTypesActionPerformed
        // TODO add your handling code here:
        //System.out.println(inputUserTypes.getSelectedItem());
    }//GEN-LAST:event_inputUserTypesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField inputName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JComboBox<String> inputUserTypes;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel login;
    private javax.swing.JLabel titlePassword;
    private javax.swing.JLabel titleTypes;
    private javax.swing.JLabel titleUser;
    // End of variables declaration//GEN-END:variables
}
